# Generated by Django 5.2.3 on 2025-06-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0006_episode_image_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnalysisResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='crawler.comment')),
            ],
        ),
    ]
