# Generated by Django 5.2.3 on 2025-06-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_episode_image_src'),
        ('llm', '0002_alter_commentanalysisresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSummaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='summary_results', to='crawler.comment')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_results', to='crawler.episode')),
            ],
        ),
    ]
