# Generated by Django 5.2.3 on 2025-07-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_comment_ai_category_comment_ai_processed_at_and_more'),
        ('llm', '0003_commentssummaryresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentssummaryresult',
            name='content',
        ),
        migrations.AlterField(
            model_name='commentssummaryresult',
            name='summary',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GenAICommentSummaryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='genai_summary_results', to='crawler.comment')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genai_summary_results', to='crawler.episode')),
            ],
        ),
    ]
