# Generated by Django 5.2.3 on 2025-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_remove_commentssummaryresult_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentssummaryresult',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentssummaryresult',
            name='source_comments',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
