# Generated by Django 5.1.3 on 2024-12-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_series_id_series_id_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='title',
            new_name='name',
        ),
    ]
