# Generated by Django 5.2 on 2025-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image_src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
