# Generated by Django 5.2.3 on 2025-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_episode_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emoticon',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
