# Generated by Django 5.2.3 on 2025-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_comment_emoticon_comment_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emoticon',
            field=models.JSONField(default=None, null=True),
        ),
    ]
