# Generated by Django 5.2.3 on 2025-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_alter_comment_emoticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
