# Generated by Django 5.2.3 on 2025-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_comment_ai_category_comment_ai_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_emotion_score',
            field=models.IntegerField(null=True),
        ),
    ]
