# Generated by Django 5.2.3 on 2025-08-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_comment_ai_emotion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
